version: "3"

services:
  api-server:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python3 manage.py migrate;
             python3 manage.py runserver 0.0.0.0:8000"
    
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /api/api-document.yaml
    volumes:
      - ./api-document.yaml:/api/api-document.yaml:ro
    ports:
      - 127.0.0.1:3000:8080
